Importar librerías

In [87]:
import pandas as pd
import numpy as np

Cargar los archivos CSV (RUTAS ABSOLUTAS)

In [88]:
# Cargar archivos CSV desde /workspace

sales = pd.read_csv("/workspace/sales.csv")
inventories = pd.read_csv("/workspace/inventories.csv")
satisfaction = pd.read_csv("/workspace/satisfaction.csv")

print("Datos de ventas")
display(sales.head())

print("Datos de inventarios")
display(inventories.head())

print("Datos de satisfacción")
display(satisfaction.head())

Datos de ventas

   ID_Tienda    Producto  Cantidad_Vendida  Precio_Unitario Fecha_Venta
0          1  Producto A                20              100  2023-01-05
1          1  Producto B                15              200  2023-01-06
2          2  Producto A                30              100  2023-01-07
3          2  Producto C                25              300  2023-01-08
4          3  Producto A                10              100  2023-01-09

Datos de inventarios

   ID_Tienda    Producto  Stock_Disponible Fecha_Actualización
0          1  Producto A                50          2023-01-05
1          1  Producto B                40          2023-01-06
2          2  Producto A                60          2023-01-07
3          2  Producto C                45          2023-01-08
4          3  Producto A                30          2023-01-09

Datos de satisfacción

   ID_Tienda  Satisfacción_Promedio Fecha_Evaluación
0          1                     85       2023-01-15
1          2                     90       2023-01-15
2          3                     70       2023-01-15
3          4                     65       2023-01-15
4          5                     55       2023-01-15

Validar estructura de los datos

In [89]:
print("Columnas de ventas:", sales.columns)
print("Columnas de inventarios:", inventories.columns)
print("Columnas de satisfacción:", satisfaction.columns)

print("\nTipos de datos ventas")
print(sales.dtypes)

Columnas de ventas: Index(['ID_Tienda', 'Producto', 'Cantidad_Vendida', 'Precio_Unitario',
       'Fecha_Venta'],
      dtype='object')
Columnas de inventarios: Index(['ID_Tienda', 'Producto', 'Stock_Disponible', 'Fecha_Actualización'], dtype='object')
Columnas de satisfacción: Index(['ID_Tienda', 'Satisfacción_Promedio', 'Fecha_Evaluación'], dtype='object')

Tipos de datos ventas
ID_Tienda            int64
Producto            object
Cantidad_Vendida     int64
Precio_Unitario      int64
Fecha_Venta         object
dtype: object

Revisar valores nulos

In [90]:
print("Valores nulos en ventas")
print(sales.isnull().sum())

print("Valores nulos en inventarios")
print(inventories.isnull().sum())

print("Valores nulos en satisfacción")
print(satisfaction.isnull().sum())

Valores nulos en ventas
ID_Tienda           0
Producto            0
Cantidad_Vendida    0
Precio_Unitario     0
Fecha_Venta         0
dtype: int64
Valores nulos en inventarios
ID_Tienda              0
Producto               0
Stock_Disponible       0
Fecha_Actualización    0
dtype: int64
Valores nulos en satisfacción
ID_Tienda                0
Satisfacción_Promedio    0
Fecha_Evaluación         0
dtype: int64

Limpieza de datos

In [91]:
sales = sales.dropna()
inventories = inventories.dropna()
satisfaction = satisfaction.dropna()

print("Dimensiones después de limpiar")

print("Ventas:", sales.shape)
print("Inventarios:", inventories.shape)
print("Satisfacción:", satisfaction.shape)

Dimensiones después de limpiar
Ventas: (10, 5)
Inventarios: (10, 4)
Satisfacción: (5, 3)

Normalizar nombres de columnas

In [92]:
sales = sales.rename(columns={
    "ID_Tienda": "store",
    "Producto": "product",
    "Cantidad_Vendida": "quantity",
    "Precio_Unitario": "price"
})

inventories = inventories.rename(columns={
    "ID_Tienda": "store",
    "Producto": "product",
    "Stock": "stock"
})

satisfaction = satisfaction.rename(columns={
    "ID_Tienda": "store",
    "Satisfaccion_Promedio": "satisfaction_score"
})

print("Columnas actualizadas ventas")
print(sales.columns)

Columnas actualizadas ventas
Index(['store', 'product', 'quantity', 'price', 'Fecha_Venta'], dtype='object')

Ventas totales por tienda

In [93]:
ventas_por_tienda = sales.groupby("store")["quantity"].sum()

print("Ventas totales por tienda")
display(ventas_por_tienda)

Ventas totales por tienda

store
1    35
2    55
3    50
4    60
5    50
Name: quantity, dtype: int64

Ventas por tienda y producto

In [94]:
ventas_producto_tienda = sales.groupby(["store","product"])["quantity"].sum()

print("Ventas por tienda y producto")
display(ventas_producto_tienda)

Ventas por tienda y producto

store  product
1      Producto A    20
       Producto B    15
2      Producto A    30
       Producto C    25
3      Producto A    10
       Producto B    40
4      Producto A    25
       Producto C    35
5      Producto B    20
       Producto C    30
Name: quantity, dtype: int64

Calcular ingresos totales

In [95]:
sales["Total_Ventas"] = sales["quantity"] * sales["price"]

ingresos_por_tienda = sales.groupby("store")["Total_Ventas"].sum()

print("Ingresos totales por tienda")
display(ingresos_por_tienda)

Ingresos totales por tienda

store
1     5000
2    10500
3     9000
4    13000
5    13000
Name: Total_Ventas, dtype: int64

Resumen estadístico de ventas

In [96]:
print("Resumen estadístico de ventas")
display(sales["Total_Ventas"].describe())

Resumen estadístico de ventas

count       10.000000
mean      5050.000000
std       3361.960407
min       1000.000000
25%       2625.000000
50%       3500.000000
75%       7875.000000
max      10500.000000
Name: Total_Ventas, dtype: float64

Preparar ventas por tienda y producto

In [97]:
ventas_tienda_producto = sales.groupby(
    ["store","product"]
)["quantity"].sum().reset_index()

display(ventas_tienda_producto.head())

   store     product  quantity
0      1  Producto A        20
1      1  Producto B        15
2      2  Producto A        30
3      2  Producto C        25
4      3  Producto A        10

Unir inventarios con ventas

In [98]:
inventarios_ventas = pd.merge(
    inventories,
    ventas_tienda_producto,
    on=["store","product"]
)

display(inventarios_ventas.head())

   store     product  Stock_Disponible Fecha_Actualización  quantity
0      1  Producto A                50          2023-01-05        20
1      1  Producto B                40          2023-01-06        15
2      2  Producto A                60          2023-01-07        30
3      2  Producto C                45          2023-01-08        25
4      3  Producto A                30          2023-01-09        10

Calcular rotación de inventario

In [101]:
inventarios_ventas["rotacion"] = (
    inventarios_ventas["quantity"] /
    inventarios_ventas["Stock_Disponible"]
)

display(inventarios_ventas.head())

   store     product  Stock_Disponible Fecha_Actualización  quantity  rotacion
0      1  Producto A                50          2023-01-05        20  0.400000
1      1  Producto B                40          2023-01-06        15  0.375000
2      2  Producto A                60          2023-01-07        30  0.500000
3      2  Producto C                45          2023-01-08        25  0.555556
4      3  Producto A                30          2023-01-09        10  0.333333

Detectar inventarios críticos (<10%)

In [104]:
inventarios_ventas["porcentaje_vendido"] = (
    (inventarios_ventas["quantity"] / inventarios_ventas["Stock_Disponible"]) * 100
)

inventario_critico = inventarios_ventas[
    inventarios_ventas["porcentaje_vendido"] < 10
]

print("Inventarios críticos")
display(inventario_critico)

Inventarios críticos

Empty DataFrame
Columns: [store, product, Stock_Disponible, Fecha_Actualización, quantity, rotacion, porcentaje_vendido]
Index: []

Análisis de satisfacción del cliente

In [105]:
print("Datos de satisfacción")
display(satisfaction.head())

Datos de satisfacción

   store  Satisfacción_Promedio Fecha_Evaluación
0      1                     85       2023-01-15
1      2                     90       2023-01-15
2      3                     70       2023-01-15
3      4                     65       2023-01-15
4      5                     55       2023-01-15

Tiendas con baja satisfacción (<60%)

In [107]:
baja_satisfaccion = satisfaction[
    satisfaction["Satisfacción_Promedio"] < 60
]

print("Tiendas con baja satisfacción")
display(baja_satisfaccion)

Tiendas con baja satisfacción

   store  Satisfacción_Promedio Fecha_Evaluación
4      5                     55       2023-01-15

Convertir ventas a NumPy

In [108]:
ventas_array = sales["Total_Ventas"].to_numpy()

Mediana de ventas

In [109]:
mediana_ventas = np.median(ventas_array)

print("Mediana de ventas:", mediana_ventas)

Mediana de ventas: 3500.0

Desviación estándar de ventas

In [110]:
desviacion_ventas = np.std(ventas_array)

print("Desviación estándar:", desviacion_ventas)

Desviación estándar: 3189.4356867634124

Simulación de ventas futuras

In [111]:
np.random.seed(42)

proyeccion_ventas = np.random.normal(
    loc=np.mean(ventas_array),
    scale=np.std(ventas_array),
    size=100
)

print("Primeras proyecciones")
print(proyeccion_ventas[:10])

Primeras proyecciones
[ 6634.23784573  4609.01490364  7115.76093733  9907.60577603
  4303.18287048  4303.23523392 10086.79771077  7497.68371242
  3552.64163948  6780.46036522]

Estadísticas de la simulación

In [112]:
print("Estadísticas de la simulación")

print("Promedio:", np.mean(proyeccion_ventas))
print("Mediana:", np.median(proyeccion_ventas))
print("Desviación estándar:", np.std(proyeccion_ventas))

Estadísticas de la simulación
Promedio: 4718.78821147718
Mediana: 4645.081072338637
Desviación estándar: 2882.025680927093

Conclusiones del análisis

- Se analizaron las ventas totales por tienda y por producto.
- Se calcularon ingresos totales generados por cada tienda.
- Se evaluó la rotación de inventarios por tienda y producto.
- Se identificaron inventarios críticos cuando el porcentaje vendido es menor al 10%.
- Se detectaron tiendas con baja satisfacción del cliente (<60%).
- Se aplicaron cálculos estadísticos con NumPy (mediana y desviación estándar).
- Se simularon proyecciones de ventas futuras usando datos históricos.